---
- hosts: dev
  become: true
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    
    - name: Install docker-py module
      apt:
        name: python3-docker
        state: present
        update_cache: yes
   
    - name: Start the container
      docker_container:
        name: hariapp
        image: fury17/hariapp:{{DOCKER_TAG}}
        state: started
        published_ports:
          - 0.0.0.0:8080:8080